col JOB_SUBNAME for a12
col CPU_USED for a24
col ELAPSED_TIME for a24
col RESOURCE_CONSUMER_GROUP for a24

select 
	SESSION_ID SID,
	OWNER,
	JOB_NAME,
	JOB_SUBNAME,
	SLAVE_PROCESS_ID SLAV_PID,
	SLAVE_OS_PROCESS_ID SLAV_OS_PID,
	RUNNING_INSTANCE INST_ID,
	RESOURCE_CONSUMER_GROUP,
	ELAPSED_TIME,
	CPU_USED
from DBA_SCHEDULER_RUNNING_JOBS
order by SID;