select TABLESPACE_NAME,
	STATUS, 
	CONTENTS, 
	EXTENT_MANAGEMENT, 
	ALLOCATION_TYPE, 
	INITIAL_EXTENT/1024/1024 as "INIT_EXT_MB",
	NEXT_EXTENT/1024/1024 as "NEXT_EXT_MB",
	SEGMENT_SPACE_MANAGEMENT, 
	RETENTION, 
	BIGFILE,
	ENCRYPTED
from dba_tablespaces
order by TABLESPACE_NAME
/
