col USER_ID for 999999
col USERNAME for a24
col ACCOUNT_STATUS for a18
col PROFILE for a14
col DEFAULT_TBS for a18
col TEMP_TBS for a18

select USER_ID, USERNAME, ACCOUNT_STATUS, LOCK_DATE, EXPIRY_DATE, CREATED,
PROFILE, DEFAULT_TABLESPACE DEFAULT_TBS, TEMPORARY_TABLESPACE TEMP_TBS
from dba_users
where ACCOUNT_STATUS like upper('%&1%')
order by USERNAME
/

undef 1
